version: '3.8'

services:
  blog_app:
    build:
      context: .  # 指定 Dockerfile 所在的目录 (当前目录)
      dockerfile: Dockerfile # 指定 Dockerfile 的名称
    container_name: blog_md # 给容器起一个自定义的名字
    restart: unless-stopped                    # 除非手动停止，否则容器会自动重启

    ports:
      - "5609:5609" # 将容器的8888端口映射到群晖的8888端口
                      # 如果群晖的8888端口已被占用，可以将前面的8888改成其他未被占用的端口

    volumes:
      # 即使代码已经构建到镜像中，我们仍然需要映射这些目录：
      # 1. contents: 你的 markdown 文件会在这里变动，chokidar 需要监听到。
      # 2. config: server.js 会写入 tree.json 到这个目录。
      # 3. public: 如果你有希望从外部直接更新的静态资源。
      # 确保这些路径相对于 docker-compose.yml 文件是正确的。
      - ./contents:/usr/src/app/contents
      - ./config:/usr/src/app/config
      - ./public:/usr/src/app/public
      - ./images:/usr/src/app/images

    # Dockerfile 中已经设置了 CHOKIDAR_USEPOLLING=true，这里可以不重复设置
    # environment:
    #   - CHOKIDAR_USEPOLLING=true